package com.rmm.recetasraquel.ui.editor

object RecipeEditorOptions {
    val categories = listOf(
        "Aperitivos",
        "Arroces",
        "Aves",
        "Bebidas",
        "Bocadillos, sándwiches y wraps",
        "Carnes",
        "Cocina internacional",
        "Conservas",
        "Desayunos",
        "Ensaladas",
        "Entrantes",
        "Guarniciones",
        "Guisos y estofados",
        "Helados y postres fríos",
        "Huevos",
        "Legumbres",
        "Mariscos",
        "Meriendas",
        "Otros",
        "Panes y masas",
        "Pasta",
        "Patatas",
        "Pescados",
        "Pizzas, empanadas y tartas saladas",
        "Platos principales",
        "Platos únicos",
        "Postres",
        "Repostería",
        "Salsas y acompañamientos",
        "Sopas y cremas",
        "Verduras y hortalizas",
    )
    val units = listOf(
        "g",
        "kg",
        "mg",
        "ml",
        "cl",
        "dl",
        "l",
        "unidad",
        "cucharadita",
        "cucharada",
        "taza",
        "vaso",
        "pizca",
        "manojo",
        "diente",
        "lata",
        "paquete",
        "sobre",
        "loncha",
        "rebanada",
        "ramita",
        "hoja",
        "al gusto",
    )
}
